# Generated by Django 3.1.13 on 2022-12-21 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20221217_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='owner',
            field=models.IntegerField(default=4, verbose_name='Venue Owner'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='phone',
            field=models.CharField(max_length=100, verbose_name='phone number'),
        ),
    ]
