# Generated by Django 4.1.4 on 2022-12-17 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_member_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='lanme',
            new_name='lname',
        ),
    ]
